import 'package:flutter/cupertino.dart';

class Profile {
  final BigInt id;
  final String imglink,
      firstname,
      mi,
      lastname,
      email,
      address,
      phonenumber,
      description,
      age,
      birthday,
      gender,
      status,
      religion,
      educcollegeprogram,
      educcollegeschool,
      educcollegedate,
      educseniorhighschool,
      educseniorhighdate,
      educjuniorhighschool,
      educjuniorhighdate,
      educprimaryschool,
      educprimarydate;

  Profile({
    @required this.id,
    @required this.imglink,
    @required this.firstname,
    @required this.mi,
    @required this.lastname,
    @required this.email,
    @required this.address,
    @required this.phonenumber,
    @required this.description,
    @required this.age,
    @required this.birthday,
    @required this.gender,
    @required this.status,
    @required this.religion,
    @required this.educcollegeprogram,
    @required this.educcollegeschool,
    @required this.educcollegedate,
    @required this.educseniorhighschool,
    @required this.educseniorhighdate,
    @required this.educjuniorhighschool,
    @required this.educjuniorhighdate,
    @required this.educprimaryschool,
    @required this.educprimarydate,
  });

  factory Profile.fromJson(Map<String, dynamic> json) {
    return Profile(
      id: json['id'] as BigInt,
      imglink: json['imglink'] as String,
      firstname: json['firstname'] as String,
      mi: json['mi'] as String,
      lastname: json['lastname'] as String,
      email: json['email'] as String,
      address: json['address'] as String,
      phonenumber: json['phonenumber'] as String,
      description: json['description'] as String,
      age: json['age'] as String,
      birthday: json['birthday'] as String,
      gender: json['gender'] as String,
      status: json['status'] as String,
      religion: json['religion'] as String,
      educcollegeprogram: json['educcollegeprogram'] as String,
      educcollegeschool: json['educcollegeschool'] as String,
      educcollegedate: json['educcollegedate'] as String,
      educseniorhighschool: json['educseniorhighschool'] as String,
      educseniorhighdate: json['educseniorhighdate'] as String,
      educjuniorhighschool: json['educjuniorhighschool'] as String,
      educjuniorhighdate: json['educjuniorhighdate'] as String,
      educprimaryschool: json['educprimaryschool'] as String,
      educprimarydate: json['educprimarydate'] as String,
    );
  }
}
